- name: mssql-rhel playbook to bind the application
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: bind-mssql-rhel
    playbook_debug: false